#KerasH5:   keras/resnet50_model.h5
#KerasH5:   keras/KERAS_mnist_cnn.h5
#KerasJson:  keras/KERAS_ecal_cnn.json
#KerasH5:    keras/KERAS_ecal_cnn.h5
#KerasJson:  keras/sho_model_arch.json
#KerasH5:    keras/sho_model_weights.h5
#KerasJson:  keras/LargeAE.json
#KerasH5:    keras/LargeAE.h5
#KerasJson:  keras/deepcalo_flat.json
#KerasH5:    keras/deepcalo_flat_weights.h5
KerasJson:  keras/DC.json
KerasH5:    keras/DC.h5
#InputData: keras/KERAS_3layer_input_features.dat
#OutputPredictions: keras/KERAS_3layer_predictions.dat
OutputDir: dc_test_2
#OutputDir: deepcalo_test_5
ProjectName: myproject
XilinxPart: xcvu9p-flgb2104-2-i
ClockPeriod: 5
Backend: Vivado

IOType: io_serial # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 20000
    Strategy: Resource
    BramFactor:    500
  LayerType:
    Dense:
      ReuseFactor: 20000
      Strategy: Resource
      Compression: False
    Conv2D:
      ReuseFactor: 20000
      Strategy: Resource
      Compression: False
